spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmrecipe_dev
    username: mmrecipe_dev_user
    password: maartenmusic
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true